spring:
  datasource:
    url: jdbc:h2:file:./data/app-db;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080

# används av vår CORS-config (kan överskridas med JVM-flagga i Run Configuration)
app:
  cors:
    allowed-origin: http://localhost:5173
